In [1]:
import numpy as np

In [2]:
#create n-dimentional numpy array

In [3]:
#create array from list

In [49]:
array=np.array([1,2,3,4])
#also can give datatype parameter eg. np.array([3,4,5],dtype=np.int32)

In [20]:
array

array([1, 2, 3, 4])

In [22]:
#number of dimensions
array.ndim

1

In [23]:
print(array)

[1 2 3 4]


In [24]:
#shape of array
array.shape
#it will show the no. of element at each dimension,in this case the no.
#of element in row

(4,)

In [25]:
#dtype--datatype of array
array.dtype

dtype('int32')

In [21]:
type(array)
#it will tell that a is a n-dimenstional arary

numpy.ndarray

In [26]:
#itemsize--size of each element in byte
array.itemsize

4

In [27]:
a=np.array([[1,2,3],[4,5,6]])

In [28]:
print(a)

[[1 2 3]
 [4 5 6]]


In [29]:
a.ndim

2

In [63]:
a.shape
#tells order of matrix.and it is in the form of tuple

(3, 5)

In [32]:
a=np.ones((2,3))
#create n dimentional array with all value 1

In [33]:
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [35]:
a=np.zeros((4,3))

In [36]:
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [37]:
a=np.empty((3,4,5))
#it will give array with random values and dtype is optional argument

In [38]:
print(a)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [39]:
a.ndim

3

In [40]:
a=np.empty((3,4))

In [41]:
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [44]:
a=np.empty((3,4,5),dtype=np.int32)
#will give random values

In [43]:
print(a)

[[[1916123064        600        194          0          0]
  [         0          0          0          0          0]
  [1936532091 1684627303  924989986  828649573 1684300345]
  [ 875770678  942683442  925905254  942892086 1650602035]]

 [[ 573662822 1937056300 1634628197  975332717 1702065442]
  [1835101810  573317733 1936942451  577662825  962798138]
  [ 895902005 1647391288 1647600993  842544693 1681404469]
  [ 892887397  875914288  740440377 1735617826 1887007839]]

 [[ 574235237 1667594341 1600484469 1970365810  578057061]
  [1702240812 1869181810  574235246  573713973 1633952300]
  [ 975332724  825242146  909126968 1412575533  859452977]
  [ 808663604  942682670 1513502264    8224034          0]]]


In [47]:
a=np.full((3,4),10)
#array of constant value

In [48]:
print(a)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [52]:
a=np.eye(4,4)
#create identity matrix

In [53]:
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [56]:
a=np.identity(5)
#create identity matrix of 5*5

In [55]:
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [57]:
a=np.diag([1,2,3,4])
#digonal matrix

In [58]:
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [61]:
a=np.random.random((3,5))
#create random matrix with values between o and 1

In [62]:
print(a)

[[0.62914708 0.68122654 0.12759222 0.59274815 0.28611912]
 [0.74576324 0.64440395 0.84199402 0.55800332 0.3079623 ]
 [0.48106932 0.86224784 0.24359768 0.4775554  0.65451409]]


In [64]:
a=np.random.randint(10,20,(3,5))
#random integer matrix.syntax--random.randint(start,end,shape).values will be
#between start value and end value

In [65]:
print(a)

[[18 13 11 18 14]
 [10 17 17 18 15]
 [19 13 13 16 10]]


In [66]:
a=np.random.uniform(1.3,5.6,(3,4))
#random float matrix between start and end

In [67]:
print(a)

[[3.56263583 4.22229435 4.15184416 1.92798431]
 [2.9656893  1.94835159 4.03265511 3.58353024]
 [5.04629376 1.96787775 5.43400008 1.44692463]]


In [68]:
a=np.random.choice([1,3,4,5],(3,4))
#syntax--random.choice(list/tuple/n-d array,shape)
#random matrix from a list of values

In [69]:
print(a)

[[4 4 4 5]
 [3 5 3 3]
 [5 3 1 3]]


In [70]:
a=np.arange(1,100,2)
#single dimension array range from start and end
#syntax--arange(start,end,steps)

In [71]:
print(a)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [1]:
#new day

In [2]:
import numpy as np

In [3]:
#arange(start,end,step)
a=np.arange(10,50,2)

In [4]:
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [5]:
a=np.arange(1.1,4.5,0.3)#for float

In [6]:
print(a)

[1.1 1.4 1.7 2.  2.3 2.6 2.9 3.2 3.5 3.8 4.1 4.4]


In [7]:
#linspace function :
#create array with n element between start and end number

In [8]:
#indices func-array represent indices of grid
a=np.indices((3,2))

In [9]:
print(a)

[[[0 0]
  [1 1]
  [2 2]]

 [[0 1]
  [0 1]
  [0 1]]]


In [10]:
#fromfuction(function,shape)

In [11]:
a=np.fromfunction(lambda x,y:x==y,(3,2))


In [12]:
a

array([[ True, False],
       [False,  True],
       [False, False]])

In [14]:
a=np.array([[1,2],[3,4]])

In [15]:
a

array([[1, 2],
       [3, 4]])

In [16]:
b=np.zeros_like(a)

In [17]:
b

array([[0, 0],
       [0, 0]])

In [24]:
b=np.empty_like(a)

In [25]:
b

array([[0, 0],
       [0, 0]])

In [22]:
b=np.full_like(a,3)

In [23]:
b

array([[3, 3],
       [3, 3]])

In [29]:
#save to file-in binary form

In [27]:
a=np.array([1,2,3,4,5,6])

In [28]:
a.tofile("array")

In [32]:
b=np.fromfile("array")

In [33]:
b

array([4.24399158e-314, 8.48798317e-314, 1.27319747e-313])

In [34]:
#also mention datatye

In [35]:
b=np.fromfile("array",dtype=np.int)

In [36]:
b

array([1, 2, 3, 4, 5, 6])

In [37]:
np.save("array2.npy",a)#pickling

In [38]:
b=np.load("array2.npy")

In [39]:
b

array([1, 2, 3, 4, 5, 6])

In [40]:
a.tofile("text",sep="$")

In [43]:
b=np.fromfile("text",sep="$",dtype=np.int)

In [44]:
b

array([1, 2, 3, 4, 5, 6])

In [45]:
a=np.arange(1,1000)

In [46]:
print(a)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 24

In [47]:
a=np.arange(1,100000)

In [48]:
print(a)

[    1     2     3 ... 99997 99998 99999]


In [49]:
#operation
#operation performed element by element

In [50]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [51]:
a+b

array([ 6,  8, 10, 12])

In [52]:
#perfom opertion element by element

In [53]:
a-b

array([-4, -4, -4, -4])

In [54]:
a*b

array([ 5, 12, 21, 32])

In [55]:
a/b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [56]:
a//b

array([0, 0, 0, 0], dtype=int32)

In [57]:
a%b

array([1, 2, 3, 4], dtype=int32)

In [58]:
print(a%b)

[1 2 3 4]


In [59]:
a**b

array([    1,    64,  2187, 65536], dtype=int32)

In [60]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [63]:
a<b
#element of a and b is comparing one by one

array([ True,  True,  True,  True])

In [62]:
a<3

array([ True,  True, False, False])

In [64]:
a>=b

array([False, False, False, False])

In [65]:
a<=b

array([ True,  True,  True,  True])

In [66]:
a>b

array([False, False, False, False])

In [67]:
a==b

array([False, False, False, False])

In [68]:
a!=b

array([ True,  True,  True,  True])

In [69]:
c=a

In [70]:
c

array([1, 2, 3, 4])

In [71]:
a+=2

In [72]:
a

array([3, 4, 5, 6])

In [73]:
a-=2

In [74]:
a*=2

In [79]:
a/=2
#why divison is not happening---a was a numeric array and on division it will give float array so it can not be happen

TypeError: No loop matching the specified signature and casting
was found for ufunc true_divide

In [76]:
a//=2

In [77]:
a%=2

In [78]:
a**=2

In [80]:
#bitwise operator


In [81]:
a|b

array([5, 6, 7, 8], dtype=int32)

In [82]:
a&b

array([1, 0, 1, 0], dtype=int32)

In [84]:
a^b

array([4, 6, 6, 8], dtype=int32)

In [85]:
~a

array([-2, -1, -2, -1], dtype=int32)

In [86]:
a<<b

array([ 32,   0, 128,   0], dtype=int32)

In [87]:
a>>b

array([0, 0, 0, 0], dtype=int32)

In [88]:
#bitwise operator with value
a&3

array([1, 0, 1, 0], dtype=int32)

In [91]:
#indexing/slicing

In [90]:
a=np.array([0,1,2,3,4,5,6,7,8,9,0])

In [92]:
a[0]

0

In [93]:
a[1]

1

In [94]:
a[-1]

0

In [95]:
a[-3]

8

In [96]:
a[1:3]

array([1, 2])

In [97]:
a[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [98]:
a[4:]

array([4, 5, 6, 7, 8, 9, 0])

In [99]:
a[::-1]

array([0, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [102]:
#boolean array--pass bollean array and it give the values where is True

In [101]:
a[[True,False,False,True,False,True,False,True,False,False,True]]

array([0, 3, 5, 7, 0])

In [103]:
#integer array

In [105]:
a[[1,6,3]]
#it gives array with the above index

array([1, 6, 3])

In [106]:
a=np.random.randint(1,30,(30))

In [107]:
a

array([23, 15,  2, 27, 25, 27,  3,  7,  1, 23,  4,  9, 22, 11, 19,  5, 13,
       11,  7, 28,  6, 22, 19, 14, 27, 17, 26,  2, 17,  2])

In [108]:
print(a)

[23 15  2 27 25 27  3  7  1 23  4  9 22 11 19  5 13 11  7 28  6 22 19 14
 27 17 26  2 17  2]


In [110]:
c=a<15

In [111]:
c

array([False, False,  True, False, False, False,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True, False,  True, False, False,  True, False, False, False,
        True, False,  True])

In [112]:
a[c]

array([ 2,  3,  7,  1,  4,  9, 11,  5, 13, 11,  7,  6, 14,  2,  2])

In [113]:
#other way
a[a<15]

array([ 2,  3,  7,  1,  4,  9, 11,  5, 13, 11,  7,  6, 14,  2,  2])

In [114]:
a[0]=34

In [115]:
a

array([34, 15,  2, 27, 25, 27,  3,  7,  1, 23,  4,  9, 22, 11, 19,  5, 13,
       11,  7, 28,  6, 22, 19, 14, 27, 17, 26,  2, 17,  2])

In [118]:
a=np.random.randint(1,30,(30))

In [119]:
a

array([ 8,  7, 26,  8, 27, 15,  4, 27, 10, 24,  1,  4,  9,  5, 13, 23, 20,
       13, 19,  5, 27, 23, 22, 28, 29, 24, 22, 25,  1, 18])

In [120]:
a[1:4]=100

In [121]:
a

array([  8, 100, 100, 100,  27,  15,   4,  27,  10,  24,   1,   4,   9,
         5,  13,  23,  20,  13,  19,   5,  27,  23,  22,  28,  29,  24,
        22,  25,   1,  18])

In [122]:
for i in a:
    print(i)

8
100
100
100
27
15
4
27
10
24
1
4
9
5
13
23
20
13
19
5
27
23
22
28
29
24
22
25
1
18


In [123]:
a=np.array([[1,2,3],[4,5,6]])

In [124]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
a[0]#show 1st row

array([1, 2, 3])

In [127]:
a[0,0]

1

In [128]:
a[0][0]

1

In [129]:
a[1][0]

4

In [130]:
a[1:2,:]

array([[4, 5, 6]])

In [131]:
a[1:2,1:2]

array([[5]])

In [132]:
a[::-1,::-1]

array([[6, 5, 4],
       [3, 2, 1]])

In [133]:
#functions

In [134]:
#flatten()--multi dimension convert to single dimension
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [135]:
#reshape()---to change shape of an array

In [136]:
a=np.arange(1,10)

In [137]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
a=np.arange(1,10).reshape(((3,3)))

In [139]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [140]:
a=np.arange(1,10).reshape((3,3))

In [141]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [142]:
a=np.arange(1,21).reshape((5,2,2))

In [143]:
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]]])

In [144]:
a.sum()


210

In [145]:
a.max()

20

In [146]:
a.min()

1

In [148]:
a=np.arange(10).reshape((5,2))

In [149]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [150]:
a.sum()

45

In [153]:
a.sum(axis=0)#show columnwis

array([20, 25])

In [154]:
a.sum(axis=1)#show row wise

array([ 1,  5,  9, 13, 17])

In [155]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [156]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,5],[6,7]])

In [158]:
a.dot(b)#give matrix multiplication

array([[16, 19],
       [36, 43]])

In [159]:
a.cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [160]:
a

array([[1, 2],
       [3, 4]])

In [161]:
a.cumsum(axis=0)

array([[1, 2],
       [4, 6]], dtype=int32)

In [162]:
np.pi

3.141592653589793

In [165]:
np.sin(a)
#element by element

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [164]:
np.cos(a)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [166]:
np.tan(a)

array([[ 1.55740772, -2.18503986],
       [-0.14254654,  1.15782128]])

In [167]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [168]:
np.exp(a)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [169]:
a=np.array([[1,2,3],[5,6,3],[6,7,4]])

In [170]:
a

array([[1, 2, 3],
       [5, 6, 3],
       [6, 7, 4]])

In [172]:
a.sort()#sort by row wise
a

array([[1, 2, 3],
       [3, 5, 6],
       [4, 6, 7]])

In [173]:
a.sort(axis=0)
a

array([[1, 2, 3],
       [3, 5, 6],
       [4, 6, 7]])

In [174]:
a.sort(axis="1",kind="quicksort")
a

TypeError: an integer is required (got type str)

In [175]:
a=np.random.random((3,2))
a

array([[0.59278322, 0.38095723],
       [0.66085418, 0.15913661],
       [0.91250918, 0.37058323]])

In [177]:
np.ceil(a)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [178]:
np.floor(a)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [180]:
np.all(a)#give true if all values are true

True

In [181]:
np.any(a)#true if  any vlaue is True


True

In [182]:
a=np.arange(10)

In [183]:
np.average(a)

4.5

In [187]:
np.mean(a)
#mean is average

4.5

In [188]:
np.median(a)
#do in sort then middle value
#median is better than mean

4.5

In [192]:
np.var(a)
#variance
#average of difference of all vlues form middle values
#check?

8.25

In [193]:
np.std(a)
#standard deviation--squareroot of varaince

2.8722813232690143

In [196]:
np.clip(a,3,8)
#it will put limit,values less than 3 will be 3 and values greater than 8 will be 8

array([3, 3, 3, 3, 4, 5, 6, 7, 8, 8])

In [195]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [197]:
a=np.random.random(10)

In [198]:
a

array([1.27969452e-01, 5.38865397e-01, 8.25667524e-01, 2.05385403e-01,
       6.21436474e-01, 6.42102171e-01, 6.34882267e-01, 8.48989623e-02,
       7.23536175e-04, 3.85194201e-01])

In [200]:
np.round(a,decimals=2)
#round off  no. in 2 decimal places

array([0.13, 0.54, 0.83, 0.21, 0.62, 0.64, 0.63, 0.08, 0.  , 0.39])

In [201]:

a

array([1.27969452e-01, 5.38865397e-01, 8.25667524e-01, 2.05385403e-01,
       6.21436474e-01, 6.42102171e-01, 6.34882267e-01, 8.48989623e-02,
       7.23536175e-04, 3.85194201e-01])

In [202]:
a=np.random.randint(1,100,30)

In [203]:
a

array([16,  4, 84, 33, 48, 10, 35, 44, 74, 59, 35, 27, 50, 71, 60, 62, 97,
       63, 59, 93, 54, 90, 63, 56, 70, 95, 61, 38, 77, 17])

In [205]:
np.where(a<10)
#it returns array of index

(array([1], dtype=int64),)

In [206]:
a[np.where(a<10)]

array([4])